# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67db63ef25e41046df1497064d53b86057b8e1d55f8f24e7eaea8b7d097849fdd8649e1a64783c8be5966a060501e5797aac1107d5626e4f3a06f2e6d85a1cc6

test:
  secret_key_base: a1328d0b6e03118851fb8558fcbf9b8c74a75cb5c4d51211bc9e9c793ffb3de59d77b3d8e1037e97cf8459abfc9f3f5b12f29ac4b1bfcc223098e1c24467bb55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
